---
title: "UConn Men's Hockey Data Analysis"
author: "Giovanni Lunetta and Alex Pugh"
execute: 
  cache: true
---

## Abstract

This study focuses on examining the relationship between power play performance and game outcomes for the UConn Men's Hockey Team across the 2019-2020 to 2021-2022 seasons. By analyzing data from 127 games, we investigate various metrics such as power play efficiency, faceoff success, zone possession percentages, and shot/goal distribution during power plays. This approach aims to provide insights into the strategic aspects of power play that most significantly impact winning games.

## Goal/Motivation

The primary goal of this analysis is to determine how different aspects of power play performance correlate with the team's success in winning games. By understanding these relationships, the team can focus on specific areas of improvement during power plays. Additionally, this analysis seeks to provide a comprehensive view of the team's power play strategies and their effectiveness, thereby aiding in tactical decision-making.

## Methods

The primary analytical technique employed in this study is logistic regression, chosen for its suitability in modeling binary outcomes, in this case, the win/loss record of the UConn Men's Hockey Team. The logistic regression model will incorporate a range of predictors related to power play performance, including scores on power plays, faceoff success rates, and shot/goal distribution. These predictors are selected based on their potential influence on game outcomes. The model will also account for variables like home advantage and opponent strength. The focus here is on the statistical approach and model specification rather than the dataset specifics, which are detailed in the "Data" section.

## Data

The dataset for this analysis includes detailed game metrics from 127 games spanning the 2019-2020 to 2021-2022 seasons. However, 18 games were excluded from the analysis for the following reasons:

- 11 games were removed because there were no powerplay faceoffs taken in the OZ during those games.
- 3 games were removed because there was no possession in the DZ during the powerplay.
- 1 game was removed because there was no possession in the OZ or the NZ during the powerplay.
- 2 games were removed due to data inconsistencies causing the possession percentage in the OZ to exceed 100% of the total elapsed time, which is not possible.

Our justification for removing these columns is as follows:

Our dataset differentiates between a 0% faceoff win rate in the offensive zone (which implies faceoffs occurred in that zone) and a '-' symbol, which indicates that no faceoffs took place in the offensive zone (this is the same for possession columns as well). It was deemed impractical to include these games, as this would distort the analysis of power play effectiveness. This reasoning is the same for the games with no possession in the DZ or OZ/NZ. The two games with possession percentages exceeding 100% were removed because this is not possible, and the data was likely entered incorrectly.

The remaining dataset and data we will use for our analysis is 110 games and 39 variables (or predictors). The variables are as follows:

Note: All variables are specifically during power plays unless otherwise stated.

- `Date` - The date the game was played
- `Opponent` - The opponent UConn played
- `Team_Total_UConn Score` - The total number of goals UConn scored
- `Team_Total_Opponent Score` - The total number of goals the opponent scored
- `Home` - Whether the game was played at home or away (1 = Home, 0 = Away)
- `Win` - Whether UConn won the game (1 = Win, 0 = Loss)
- `Team_Score_On_PP` - Whether UConn scored on the power play (1 = Score, 0 = No Score)
- `Team_PP_Faceoffs won in OZ, %` - The percentage of faceoffs won in the offensive zone
- `Team_PP_Faceoffs won, %` - The percentage of faceoffs won
- `Team_Shots_OT_Behind_Net` - The number of shots taken behind the net that were on target
- `Team_Shots_Behind_Net` - The number of shots taken behind the net
- `Team_Goals_Behind_Net` - The number of goals scored behind the net
- `Team_Shots_OT_at_Net` - The number of shots taken at the net that were on target
- `Team_Shots_at_Net` - The number of shots taken at the net
- `Team_Goals_at_Net` - The number of goals scored at the net
- `Team_Shots_OT_Left_Close` - The number of shots taken on the left side of the net that were on target
- `Team_Shots_Left_Close` - The number of shots taken on the left side of the net
- `Team_Goals_Left_Close` - The number of goals scored on the left side of the net
- `Team_Shots_OT_Center_Close` - The number of shots taken in the center of the net that were on target
- `Team_Shots_Center_Close` - The number of shots taken in the center of the net
- `Team_Goals_Center_Close` - The number of goals scored in the center of the net
- `Team_Shots_OT_Right_Close` - The number of shots taken on the right side of the net that were on target
- `Team_Shots_Right_Close` - The number of shots taken on the right side of the net
- `Team_Goals_Right_Close` - The number of goals scored on the right side of the net
- `Team_Shots_OT_Left_Far` - The number of shots taken on the left side of the net that were on target
- `Team_Shots_Left_Far` - The number of shots taken on the left side of the net
- `Team_Goals_Left_Far` - The number of goals scored on the left side of the net
- `Team_Shots_OT_Center_Far` - The number of shots taken in the center of the net that were on target
- `Team_Shots_Center_Far` - The number of shots taken in the center of the net
- `Team_Goals_Center_Far` - The number of goals scored in the center of the net
- `Team_Shots_OT_Right_Far` - The number of shots taken on the right side of the net that were on target
- `Team_Shots_Right_Far` - The number of shots taken on the right side of the net 
- `Team_Goals_Right_Far` - The number of goals scored on the right side of the net
- `Team_Shots_OT_Not_in_Offensive_Zone` - The number of shots taken that were on target but not in the offensive zone
- `Team_Shots_Not_in_Offensive_Zone` - The number of shots taken that were not in the offensive zone
- `Team_Goals_Not_in_Offensive_Zone` - The number of goals scored that were not in the offensive zone
- `Team_PP_OZ possession, %` - The percentage of time UConn had possession in the offensive zone
- `Team_PP_NZ possession, %` - The percentage of time UConn had possession in the neutral zone
- `Team_PP_DZ possession, %` - The percentage of time UConn had possession in the defensive zone


## Analysis
Lets start by getting a look at the data. We can sample 5 of the games:
```{python}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

df = pd.read_csv('/Users/giovanni-lunetta/uconn_masters/hockey/hockey_repo/data/final_data.csv', low_memory=False)


pd.set_option('display.max_columns', None)
df.sample(5)
```


As well as look at the summary statistics for each variable:
```{python}
df.describe()
```


## Analysis (cont.)

We can also visualize the distribution of our dependent variable, `win`. 
```{python}
# Plotting the distribution of the dependent variable 'Win'
plt.figure(figsize=(8, 5))
sns.countplot(x='Win', data=df)
plt.title('Distribution of Wins')
plt.xlabel('Win (0 = Loss, 1 = Win)')
plt.ylabel('Count')
plt.show()
```



## Analysis (cont.)

```{python}
# Removing the duplicate column 'Team_Shots_Behind_Net'
df = df.drop('Team_Shots_Behind_Net', axis=1)

# Checking for columns that have all zeros
columns_all_zeros = df.columns[(df == 0).all()]
columns_all_zeros

# Dropping columns with all zeros
df = df.drop(columns=columns_all_zeros)

# Dropping non-numeric columns for simplicity
df = df.drop(columns=['Date', 'Opponent'])
df = df.drop(columns=['Team_Total_UConn_Score', 'Team_Total_Opponent_Score'])
df = df.drop(columns=['Team_Shots_OT_Behind_Net'])
df = df.drop(columns=['Team_PP_Faceoffs_won_in_OZ_percent'])
```

After some preprocessing we can run the logistic regression model:

```{python}
import statsmodels.formula.api as smf

# Joining all column names with '+' except 'Win', 'Date', and 'Opponent'
formula = 'Win ~ ' + ' + '.join(df.columns.drop('Win'))

# Fitting the logistic regression model using smf.logit
logit_model = smf.logit(formula=formula, data=df).fit()

# Displaying the summary of the model
logit_model_summary = logit_model.summary()
print(logit_model_summary)
```

## Analysis (cont.)

Before commenting on the results, we can confirm that the underlying assumptions are not violated by checking residuals and multicollinearity Because games deemed to be "outliers" can still be useful in our analysis, we will not remove any data points. We also do not check for independence as this is satisfied by the nature of the data.
```{python}
import matplotlib.pyplot as plt

residuals = logit_model.resid_generalized
plt.hist(residuals, bins=20)
```

```{python}
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Selecting only the independent variables
X = df.drop('Win', axis=1)

# Calculating VIF for each feature
vif_data = pd.DataFrame()
vif_data['feature'] = X.columns
vif_data['VIF'] = [variance_inflation_factor(X.values, i) for i in range(len(X.columns))]

vif_data.sort_values(by='VIF', ascending=False)

df = df.drop(columns=['Team_Shots_OT_at_Net'])
```

The residuals are normally distributed, and the only variable of concern in terms of multicollinearity is `Team_Shots_OT_at_Net` which we removed. This variable is intuitively highly correlated with 'Team_Shots_at_Net' as a very high proportion of shots at the net are on target. This is confirmed by the VIF values, which were both near 20 before dropping this variable.

We also saw that the model was not able to converge, which is likely due to the fact that some variables have very large coefficients, most likely due to their high variability where the model is unable to converge to a solution. We drop these columns as well.

```{python}
df = df.drop(columns=['Team_Goals_Right_Close', 'Team_Goals_Left_Far', 'Team_Goals_Center_Far', 'Team_Goals_Right_Far', 'Team_Shots_OT_Not_in_Offensive_Zone', 'Team_Shots_Not_in_Offensive_Zone'])
```

## Analysis (cont.)

Now we can rerun the model and look at performance metrics:
```{python}
import statsmodels.formula.api as smf

# Joining all column names with '+' except 'Win', 'Date', and 'Opponent'
formula = 'Win ~ ' + ' + '.join(df.columns.drop('Win'))

# Fitting the logistic regression model using smf.logit
logit_model = smf.logit(formula=formula, data=df).fit()

# Displaying the summary of the model
logit_model_summary = logit_model.summary()
print(logit_model_summary)
```

```{python}
from sklearn.metrics import roc_curve, auc

predictions = logit_model.predict(df)

fpr, tpr, thresholds = roc_curve(df['Win'], predictions)
roc_auc = auc(fpr, tpr)

plt.figure()
plt.plot(fpr, tpr, color='darkorange', lw=2, label='ROC curve (area = %0.2f)' % roc_auc)
plt.plot([0, 1], [0, 1], color='navy', lw=2, linestyle='--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('Receiver Operating Characteristic')
plt.legend(loc="lower right")
plt.show()
```

```{python}
from sklearn.metrics import confusion_matrix
import seaborn as sns

# Convert probabilities to 0/1 predictions based on a chosen threshold (e.g., 0.5)
pred_labels = predictions > 0.5
cm = confusion_matrix(df['Win'], pred_labels)

sns.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('True')
plt.show()
```

```{python}
import numpy as np
import statsmodels.api as sm

# Assuming logit_model is your fitted logistic regression model
# And X_test is your test features dataset

predicted_probabilities = logit_model.predict(X)
predicted_labels = np.where(predicted_probabilities > 0.5, 1, 0)  # Using 0.5 as the threshold


from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

precision = precision_score(df['Win'], predicted_labels)
recall = recall_score(df['Win'], predicted_labels)
f1 = f1_score(df['Win'], predicted_labels)
accuracy = accuracy_score(df['Win'], predicted_labels)

print(f"Precision: {precision}")
print(f"Recall: {recall}")
print(f"F1-Score: {f1}")
print(f"Accuracy: {accuracy}")
```

## Analysis of Results

Now we can comment on the results:

Intercept: The model's intercept is significant, indicating that even when all predictor variables are at zero, the log odds of winning vs. losing are significantly different from zero.

Home (p = 0.393): This variable is not statistically significant, suggesting that playing at home does not significantly impact the likelihood of winning in this model.

Team_Score_On_PP (p = 0.361): Scoring on the power play is not a significant predictor of winning games, according to the model. This might seem counterintuitive, but it could indicate that other aspects of power play performance are more critical.

Team_PP_Faceoffs_won_percent (p = 0.018): This variable is significant, showing that winning a higher percentage of faceoffs during power plays is positively correlated with winning games.

Team_Shots_at_Net (p = 0.052): Though borderline, this variable is not statistically significant at the 0.05 level. It suggests that the number of shots at the net during power plays doesn't have a statistically significant effect on winning games.

Team_Goals_at_Net (p = 0.479): The number of goals scored at the net during power plays is not a significant predictor of winning games.

Team_Shots_OT_Left_Close (p = 0.181): Shots on target from the left close range are not a significant predictor of winning.

Team_Shots_Left_Close (p = 0.364): Similarly, the total number of shots from the left close range does not significantly impact the likelihood of winning.

Team_Goals_Left_Close (p = 0.408): The number of goals scored from the left close range is not a significant predictor.

Team_Shots_OT_Center_Close (p = 0.958): Shots on target from the center close range do not significantly impact winning chances.

Team_Shots_Center_Close (p = 0.288): The total number of shots from the center close range is not a significant predictor.

Team_Goals_Center_Close (p = 0.170): Goals scored from the center close range also do not significantly affect the chances of winning.

Team_Shots_OT_Right_Close (p = 0.233): Shots on target from the right close range are not a significant predictor.

Team_Shots_Right_Close (p = 0.717): The total number of shots from the right close range does not significantly influence game outcomes.

Team_Shots_OT_Left_Far (p = 0.975): Shots on target from the left far range are not a significant predictor.

Team_Shots_Left_Far (p = 0.622): The total number of shots from the left far range does not significantly impact the likelihood of winning.

Team_Shots_OT_Center_Far (p = 0.790): Shots on target from the center far range are not significant predictors of winning games.

Team_Shots_Center_Far (p = 0.278): The total number of shots from the center far range is not a significant predictor.

Team_Shots_OT_Right_Far (p = 0.658): Shots on target from the right far range do not significantly impact winning chances.

Team_Shots_Right_Far (p = 0.470): The total number of shots from the right far range is not a significant predictor.

Team_PP_OZ_possession_percent (p = 0.039): The percentage of time possessing the puck in the offensive zone during power plays is significant, suggesting a positive impact on winning games.

Team_PP_NZ_possession_percent (p = 0.131): Possession in the neutral zone during power plays is not a significant predictor of winning.

Team_PP_DZ_possession_percent (p = 0.208): Similarly, possession in the defensive zone during power plays does not significantly influence game outcomes.

In summary, the most significant factors at the 0.05 alpha level are winning faceoffs during power plays and maintaining possession in the offensive zone. Many of the shot-related variables, both in terms of attempts and goals, did not emerge as significant predictors in this model. This analysis provides a nuanced understanding of what aspects of power play performance are most crucial to game outcomes for the UConn Men's Hockey Team.

Additionally, the model’s ROC curve area of 0.76 suggests a good discriminatory ability between winning and losing outcomes. Also, Precision, Recall, and F1-Score values (0.71, 0.77, and 0.74 respectively) indicate a balanced and effective model in predicting game outcomes.

## Discussion & Conclusion

### Discussion

#### Interpretation of Key Findings

Our logistic regression analysis reveals intriguing insights into the dynamics of power play performance and their impact on game outcomes for the UConn Men's Hockey Team. The significance of certain variables over others provides a nuanced understanding of strategic elements in hockey.

1. **Significance of Faceoffs (Team_PP_Faceoffs_won_percent)**:
   - The statistical significance of faceoff wins during power plays underscores the tactical advantage of gaining initial control of the puck. Winning faceoffs sets the tone for the subsequent play, allowing for immediate offensive pressure and potentially disorganizing the opponent's defense.

2. **Offensive Zone Possession (Team_PP_OZ_possession_percent)**:
   - The positive correlation between offensive zone possession during power plays and winning outcomes suggests the importance of sustained offensive pressure. It highlights the need for effective puck handling and strategic positioning to maintain control in the offensive zone.

3. **Non-significance of Shot and Goal Metrics**:
   - Interestingly, most variables related to shots and goals, whether from close or far ranges, did not significantly predict winning outcomes. This might indicate that the sheer number of shots or goals during power plays isn't as crucial as the quality and strategic execution of these shots. It also suggests that other factors, like defensive strategies or goaltending, play a significant role in determining the success of power plays.

4. **Home Advantage (Home)**:
   - The lack of statistical significance for the 'Home' variable suggests that the home-ice advantage, often considered an influential factor in sports, may not be as impactful in determining the outcomes of the games within the scope of this analysis. This could be due to a well-adapted team performance irrespective of the venue or other balancing factors like travel fatigue not being captured in the model.

#### Limitations

While our analysis provides valuable insights, it is crucial to acknowledge its limitations:

- **Data Scope**: Our analysis is confined to three seasons of data. Longer-term trends or changes in team composition and strategy over time are not captured.
- **Unmeasured Factors**: Intangible elements like team morale, player injuries, psychological factors, and the quality of opposition strategies are not quantified in our dataset but can significantly influence game outcomes.
- **Model Constraints**: The logistic regression model, while robust, may not capture the complex interactions and non-linear relationships that can exist in sports data.

#### Recommendations

Based on our findings, we recommend:

1. **Strategic Emphasis on Faceoffs and Offensive Zone Control**: Coaches and players should focus on strategies and training drills that enhance faceoff success and control in the offensive zone.
2. **Quality Over Quantity in Shot Taking**: Rethink the approach to shooting, emphasizing strategic and well-positioned shots over mere volume. Location of shot attempts are not likely to be as significant of a factor as the quality of the shot.

### Conclusion

Our logistic regression analysis has shed light on the complex interplay of factors that contribute to successful outcomes in hockey, particularly during power plays. The significant role of faceoff wins and offensive zone possession during power plays emerged as key strategic elements. Contrary to conventional wisdom, the number of shots or goals during power plays was not predictive of winning outcomes, suggesting a need to focus on the quality and execution of offensive strategies. 

This analysis serves as a foundational piece for the UConn Men's Hockey Team in formulating data-driven strategies. It encourages a nuanced approach to understanding the multifaceted nature of hockey and the variables that influence game outcomes. Future analyses could expand on this work by incorporating a broader dataset, considering additional variables, and employing more complex statistical models to capture the dynamic nature of the sport.



